version: '3.3'

services:
  sub1a:
    container_name: sub1a
    build: ./sub1a
    tty: true
    hostname: sub1a
    networks:
      - subnet1
    cap_add:
      - NET_ADMIN
  sub1b:
    container_name: sub1b
    image: alpine:latest
    tty: true
    hostname: sub1b
    networks:
      - subnet1
  sub2a:
    container_name: sub2a
    image: alpine:latest
    tty: true
    hostname: sub2a
    networks:
      - subnet2
  sub_hub:
    container_name: sub_hub
    build: ./sub_hub
    tty: true
    hostname: sub_hub
    networks:
      subnet1:
          ipv4_address: 172.30.1.64
      subnet2:
    cap_add:
      - NET_ADMIN


networks:
  subnet1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
  subnet2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.2.0/24

